CyberWebsite/CyberWebsite/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CyberWebsite.Models;

namespace CyberWebsite.Controllers
{
    
    public class AdminController : Controller
    {
        CyberWebsiteEntities cyberDB = new CyberWebsiteEntities();
        public ActionResult Index()
        {
            return View();
        }
	}
}

CyberWebsite/CyberWebsite/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using CyberWebsite.Models;

namespace CyberWebsite.Controllers
{
    public class CategoriesController : Controller
    {
        CyberWebsiteEntities cyberDB = new CyberWebsiteEntities();
        public ActionResult Index()
        {
            IList<Categories> model = cyberDB.Categories.ToList();

            return View(model);
        }

        public ActionResult Edit(int id)
        {

            Models.Categories model = cyberDB.Categories.First(x => x.Id == id);

            return View(model);

        }
        [HttpPost]
        public ActionResult Edit(Categories model)
        {

            cyberDB.Categories.AddOrUpdate(model);
            cyberDB.SaveChanges();

            return RedirectToAction("Index");

        }

        public ActionResult Create()
        {
            Categories model = new Categories();

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(Categories model)
        {
            cyberDB.Categories.Add(model);
            cyberDB.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            Models.Categories model = cyberDB.Categories.First(x => x.Id == id);

            cyberDB.Categories.Remove(model);
            cyberDB.SaveChanges();

            return RedirectToAction("Index");

        }

        public PartialViewResult _CategoryList(int id)
        {
            IList<Categories> model = null;
            //Gets the category
            Categories category = cyberDB.Categories.First(x => x.Id == id);

            //If category is root, get all subcategories
            if (category.IdParent == 0)
            {
                model = cyberDB.Categories.Where(x => x.IdParent == category.Id).ToList();
            }
            else //Check get all parent's subcategories
            {
                model = cyberDB.Categories.Where(x => x.IdParent == category.IdParent).ToList();
            }

            return PartialView(model);
        }

	}
}

CyberWebsite/CyberWebsite/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CyberWebsite.Models;

namespace CyberWebsite.Controllers
{
    public class ProductController : Controller
    {
        CyberWebsiteEntities cyberDB = new CyberWebsiteEntities();
        public ActionResult Index(int id)
        {
            return View();
        }

        public ActionResult ProductsInCategory(int id)
        {

            ViewBag.CategoryName = cyberDB.Categories.First(x => x.Id == id).Description;
            ViewBag.CategoryId = id;

            return View();
        }

        public ActionResult Index()
        {
            return View();
        }
	}
}

CyberWebsite/CyberWebsite/Views/Home/About.cshtml
@{
   ViewBag.Title = "About";
}

<h2>About us the students</h2>

CyberWebsite/CyberWebsite/Views/Product/ProductsInCategory.cshtml
@model CyberWebsite.Models.Categories

@{
    ViewBag.Title = ViewBag.CategoryName;
    int categoryId = ViewBag.CategoryId;
}

<h2>@ViewBag.CategoryName</h2>

<div class="row">
    <div class="col-md-4">
        <!-- renders a partial view with the subcategories -->
        @{ Html.RenderAction("_CategoryList", "Categories", new { id = categoryId }); }
    </div>
    <div class="col-md-8">
        @if (categoryId < 10)
        { <h2>Kies een Robot</h2> }
                                  else
        { 
       
        }
       @{Html.RenderAction("_ProductInfo", "Product");}
    </div>
</div>

CyberWebsite/CyberWebsite/Views/Product/_ProductInfo.cshtml
@model IEnumerable<CyberWebsite.Models.Categories>

<h3>Sub-categories</h3>
<p>
    Hier moet dan de info pagina van de @ViewBag.CategoryName laden!
    Maar hoe? Dus ik moet de _ProductInfo uit de map Product hier laden,
    ik dacht dat het met Html.RenderAction("_ProductInfo", "Product") wel kon,
    maar dat dacht ik dus mooi even fout
</p>